In [1]:
import pandas as pd

In [2]:
my_data = {
    'cars' : ['BMW', 'Volvo', 'Ford'],
    'prices' : [30000, 25000, 27000]
}
print(my_data, type(my_data))

{'cars': ['BMW', 'Volvo', 'Ford'], 'prices': [30000, 25000, 27000]} <class 'dict'>

In [3]:
df_cars = pd.DataFrame(my_data)
df_cars.head()

    cars  prices
0    BMW   30000
1  Volvo   25000
2   Ford   27000

In [4]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cars    3 non-null      object
 1   prices  3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [6]:
print(df_cars.isnull())

    cars  prices
0  False   False
1  False   False
2  False   False

In [22]:
my_data = {
    'cars' : ['BMW', 'Volvo', 'Ford', None, 'Mazda'],
    'prices' : [30000, None, 25000, 27000, None]
}
df_cars = pd.DataFrame(my_data)
df_cars.head()

    cars   prices
0    BMW  30000.0
1  Volvo      NaN
2   Ford  25000.0
3   None  27000.0
4  Mazda      NaN

In [8]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cars    4 non-null      object
 1   prices  3 non-null      float64
dtypes: float64(1), object(1)
memory usage: 212.0+ bytes

In [9]:
df_cars.isnull()

    cars  prices
0  False   False
1  False    True
2  False   False
3   True   False
4  False    True

In [11]:
df_cars_cleaned = df_cars.dropna()
print(df_cars_cleaned)

   cars   prices
0   BMW  30000.0
2  Ford  25000.0

In [14]:
df_cars_cleaned.reset_index()
print(df_cars_cleaned)

   index  cars   prices
0      0   BMW  30000.0
1      2  Ford  25000.0

In [15]:
df_cars.head()

    cars   prices
0    BMW  30000.0
1  Volvo      NaN
2   Ford  25000.0
3   None  27000.0
4  Mazda      NaN

In [17]:
df_cars_cleaned = df_cars.fillna(0)
df_cars_cleaned.head()

    cars   prices
0    BMW  30000.0
1  Volvo      0.0
2   Ford  25000.0
3      0  27000.0
4  Mazda      0.0

In [18]:
# fill NA on prices column only
df_cars['prices'] = df_cars['prices'].fillna(0)
df_cars.head()

    cars   prices
0    BMW  30000.0
1  Volvo      0.0
2   Ford  25000.0
3   None  27000.0
4  Mazda      0.0

In [19]:
df_cars['cars'] = df_cars['cars'].fillna('Unknown Car')
df_cars.head()

          cars   prices
0          BMW  30000.0
1        Volvo      0.0
2         Ford  25000.0
3  Unknown Car  27000.0
4        Mazda      0.0

In [20]:
print(type(df_cars))

<class 'pandas.core.frame.DataFrame'>

In [24]:
df_cars.head()

    cars   prices
0    BMW  30000.0
1  Volvo      NaN
2   Ford  25000.0
3   None  27000.0
4  Mazda      NaN

In [ ]:
avg_price = df_cars['prices'].mean()    # .min(), .max()
print(f'Average price of cars: {avg_price}')

Average price of cars: 27333.333333333332

In [25]:
# df_cars['prices'] = df_cars['prices'].fillna(df_cars['prices'].mean())
df_cars['prices'] = df_cars['prices'].fillna(avg_price)

In [26]:
df_cars.head()

    cars        prices
0    BMW  30000.000000
1  Volvo  27333.333333
2   Ford  25000.000000
3   None  27000.000000
4  Mazda  27333.333333

In [27]:
df_sub_cars = df_cars.loc[[0, 2]]
df_sub_cars.head()

   cars   prices
0   BMW  30000.0
2  Ford  25000.0

In [28]:
my_data = {
    'cars' : ['BMW', 'Volvo', 'Ford'],
    'prices' : [30000, 25000, 27000]
}

df_cars = pd.DataFrame(my_data, index=['CAR01', 'CAR02', 'CAR03'])
df_cars.head()

        cars  prices
CAR01    BMW   30000
CAR02  Volvo   25000
CAR03   Ford   27000

In [33]:
# Using groupby
dept = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR'],
    'Salary': [60000, 75000, 80000, 90000, 65000]
}
df_dept = pd.DataFrame(dept)
print(df_dept)

  Employee Department  Salary
0    Alice         HR   60000
1      Bob         IT   75000
2  Charlie         IT   80000
3    David    Finance   90000
4      Eva         HR   65000

In [35]:
df_group_dept = df_dept.groupby('Department')
print(df_group_dept['Salary'].mean())

Department
Finance    90000.0
HR         62500.0
IT         77500.0
Name: Salary, dtype: float64

In [36]:
print(df_group_dept['Salary'].sum())

Department
Finance     90000
HR         125000
IT         155000
Name: Salary, dtype: int64

In [37]:
print(df_group_dept['Salary'].min())

Department
Finance    90000
HR         60000
IT         75000
Name: Salary, dtype: int64

In [38]:
# get data by column
df_dept['Employee']

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Employee, dtype: object

In [42]:
print(df_dept.loc[0])

Employee      Alice
Department       HR
Salary        60000
Name: 0, dtype: object

In [43]:
print(df_dept)

  Employee Department  Salary
0    Alice         HR   60000
1      Bob         IT   75000
2  Charlie         IT   80000
3    David    Finance   90000
4      Eva         HR   65000

In [45]:
df_dept['Bonus'] = [5000, 7000, 6000, 8000, 5500]

In [46]:
print(df_dept)

  Employee Department  Salary  Bonus
0    Alice         HR   60000   5000
1      Bob         IT   75000   7000
2  Charlie         IT   80000   6000
3    David    Finance   90000   8000
4      Eva         HR   65000   5500

In [47]:
df_old = df_dept.drop('Bonus', axis=1)
print(df_old)

  Employee Department  Salary
0    Alice         HR   60000
1      Bob         IT   75000
2  Charlie         IT   80000
3    David    Finance   90000
4      Eva         HR   65000

In [48]:
print(df_dept)

  Employee Department  Salary  Bonus
0    Alice         HR   60000   5000
1      Bob         IT   75000   7000
2  Charlie         IT   80000   6000
3    David    Finance   90000   8000
4      Eva         HR   65000   5500

In [49]:
df_dept.drop('Bonus', axis=1, inplace=True) # modify the original DataFrame
print(df_dept)

  Employee Department  Salary
0    Alice         HR   60000
1      Bob         IT   75000
2  Charlie         IT   80000
3    David    Finance   90000
4      Eva         HR   65000

In [51]:
df_dept.loc[1, 'Salary'] = 1000000
print(df_dept)

  Employee Department   Salary
0    Alice         HR  1000000
1      Bob         IT  1000000
2  Charlie         IT    80000
3    David    Finance    90000
4      Eva         HR    65000

In [52]:
dept = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR'],
    'Salary': [60000, 75000, 80000, 90000, 65000]
}
df_dept = pd.DataFrame(dept)
print(df_dept)

  Employee Department  Salary
0    Alice         HR   60000
1      Bob         IT   75000
2  Charlie         IT   80000
3    David    Finance   90000
4      Eva         HR   65000

In [54]:
df_sorted = df_dept.sort_values(by='Salary', ascending=True)
print(df_sorted)

  Employee Department  Salary
0    Alice         HR   60000
4      Eva         HR   65000
1      Bob         IT   75000
2  Charlie         IT   80000
3    David    Finance   90000

In [56]:
df_training = pd.read_csv('datab7.csv')
df_training.head(10)

   Duration  Pulse  Maxpulse  Calories
0      60.0  110.0     130.0     409.1
1      60.0  117.0     145.0     479.0
2      60.0  103.0     135.0     340.0
3      45.0  109.0     175.0     282.4
4      45.0    NaN     148.0     406.0
5      60.0  102.0     127.0     300.0
6      60.0  110.0     136.0     374.0
7      45.0  104.0     134.0     253.3
8      30.0  109.0     133.0     195.1
9      60.0   98.0     124.0     269.0

In [57]:
df_training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  170 non-null    float64
 1   Pulse     171 non-null    float64
 2   Maxpulse  171 non-null    float64
 3   Calories  167 non-null    float64
dtypes: float64(4)
memory usage: 5.5 KB

In [58]:
# calculate sum of null values in each column
null_sum = df_training.isnull().sum()
print(null_sum)

Duration    2
Pulse       1
Maxpulse    1
Calories    5
dtype: int64

In [59]:
df_training.dropna(inplace=True)
df_training.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163 entries, 0 to 171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  163 non-null    float64
 1   Pulse     163 non-null    float64
 2   Maxpulse  163 non-null    float64
 3   Calories  163 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [60]:
df_training.describe()

         Duration       Pulse    Maxpulse     Calories
count  163.000000  163.000000  163.000000   163.000000
mean    64.447853  107.705521  134.478528   375.912883
std     42.975754   14.666638   16.628229   267.102181
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.850000
50%     60.000000  106.000000  131.000000   319.200000
75%     60.000000  111.000000  143.500000   385.800000
max    300.000000  159.000000  184.000000  1860.400000

In [61]:
df_training = pd.read_csv('datab7.csv')
df_training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  170 non-null    float64
 1   Pulse     171 non-null    float64
 2   Maxpulse  171 non-null    float64
 3   Calories  167 non-null    float64
dtypes: float64(4)
memory usage: 5.5 KB

In [62]:
df_training.dropna(subset=['Calories'], inplace=True)
df_training.info()

<class 'pandas.core.frame.DataFrame'>
Index: 167 entries, 0 to 171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  165 non-null    float64
 1   Pulse     166 non-null    float64
 2   Maxpulse  166 non-null    float64
 3   Calories  167 non-null    float64
dtypes: float64(4)
memory usage: 6.5 KB

In [63]:
df_training.dropna(inplace=True)
df_training.info()

<class 'pandas.core.frame.DataFrame'>
Index: 163 entries, 0 to 171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  163 non-null    float64
 1   Pulse     163 non-null    float64
 2   Maxpulse  163 non-null    float64
 3   Calories  163 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [64]:
df_training = pd.read_csv('datab7.csv')
df_training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  170 non-null    float64
 1   Pulse     171 non-null    float64
 2   Maxpulse  171 non-null    float64
 3   Calories  167 non-null    float64
dtypes: float64(4)
memory usage: 5.5 KB

In [65]:
df_training.describe()

        Duration       Pulse    Maxpulse     Calories
count  170.00000  171.000000  171.000000   167.000000
mean    64.00000  107.508772  134.321637   375.304192
std     42.15918   14.447214   16.401813   264.009282
min     15.00000   80.000000  100.000000    50.300000
25%     45.00000  100.000000  124.000000   252.150000
50%     60.00000  105.000000  131.000000   320.400000
75%     60.00000  111.000000  143.000000   385.800000
max    300.00000  159.000000  184.000000  1860.400000

In [66]:
df_training['Duration'].fillna(df_training['Duration'].mean(), inplace=True)
df_training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  172 non-null    float64
 1   Pulse     171 non-null    float64
 2   Maxpulse  171 non-null    float64
 3   Calories  167 non-null    float64
dtypes: float64(4)
memory usage: 5.5 KB

/var/folders/10/3dssf0p51vzgb7zfm9xl0vrm0000gn/T/ipykernel_79892/2112045139.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_training['Duration'].fillna(df_training['Duration'].mean(), inplace=True)

In [67]:
df_training.describe()

        Duration       Pulse    Maxpulse     Calories
count  172.00000  171.000000  171.000000   167.000000
mean    64.00000  107.508772  134.321637   375.304192
std     41.91191   14.447214   16.401813   264.009282
min     15.00000   80.000000  100.000000    50.300000
25%     45.00000  100.000000  124.000000   252.150000
50%     60.00000  105.000000  131.000000   320.400000
75%     60.00000  111.000000  143.000000   385.800000
max    300.00000  159.000000  184.000000  1860.400000

In [68]:
df_training['Pulse'].fillna(df_training['Pulse'].min(), inplace=True)
df_training.describe()

/var/folders/10/3dssf0p51vzgb7zfm9xl0vrm0000gn/T/ipykernel_79892/1012710417.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_training['Pulse'].fillna(df_training['Pulse'].min(), inplace=True)

        Duration       Pulse    Maxpulse     Calories
count  172.00000  172.000000  171.000000   167.000000
mean    64.00000  107.348837  134.321637   375.304192
std     41.91191   14.556819   16.401813   264.009282
min     15.00000   80.000000  100.000000    50.300000
25%     45.00000  100.000000  124.000000   252.150000
50%     60.00000  105.000000  131.000000   320.400000
75%     60.00000  111.000000  143.000000   385.800000
max    300.00000  159.000000  184.000000  1860.400000

In [69]:
df_training['Maxpulse'].fillna(df_training['Maxpulse'].max(), inplace=True)
df_training.describe()

/var/folders/10/3dssf0p51vzgb7zfm9xl0vrm0000gn/T/ipykernel_79892/4012329385.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_training['Maxpulse'].fillna(df_training['Maxpulse'].max(), inplace=True)

        Duration       Pulse    Maxpulse     Calories
count  172.00000  172.000000  172.000000   167.000000
mean    64.00000  107.348837  134.610465   375.304192
std     41.91191   14.556819   16.786743   264.009282
min     15.00000   80.000000  100.000000    50.300000
25%     45.00000  100.000000  124.000000   252.150000
50%     60.00000  105.000000  131.500000   320.400000
75%     60.00000  111.000000  143.250000   385.800000
max    300.00000  159.000000  184.000000  1860.400000

In [70]:
# get unique duration
print(df_training['Duration'].unique())

[ 60.  45.  30.  80.  20. 210. 160.  64. 180. 150. 300.  90. 120. 270.
  15.  25.  75.]

In [71]:
df_gr_duration = df_training.groupby('Duration')
print(df_gr_duration['Calories'].mean())

Duration
15.0       87.350000
20.0      151.600000
25.0      244.200000
30.0      192.125000
45.0      271.118750
60.0      339.728571
64.0      361.500000
75.0      323.733333
80.0      643.100000
90.0      541.800000
120.0     666.833333
150.0     939.400000
160.0     943.700000
180.0     733.600000
210.0    1618.200000
270.0    1729.000000
300.0    1500.200000
Name: Calories, dtype: float64

In [72]:
print(df_gr_duration['Pulse'].mean())

Duration
15.0     102.000000
20.0     125.000000
25.0     152.000000
30.0     109.812500
45.0     106.088235
60.0     106.187500
64.0     113.500000
75.0     121.666667
80.0     123.000000
90.0      93.750000
120.0    100.000000
150.0    101.500000
160.0    109.500000
180.0     93.666667
210.0    122.500000
270.0    100.000000
300.0    108.000000
Name: Pulse, dtype: float64

In [75]:
print(df_gr_duration['Maxpulse'].mean())

Duration
15.0     119.500000
20.0     146.000000
25.0     168.000000
30.0     137.000000
45.0     133.000000
60.0     133.975000
64.0     134.000000
75.0     150.000000
80.0     146.000000
90.0     116.375000
120.0    139.000000
150.0    130.250000
160.0    136.000000
180.0    125.666667
210.0    172.000000
270.0    131.000000
300.0    143.000000
Name: Maxpulse, dtype: float64

In [76]:
df_training.head()

   Duration  Pulse  Maxpulse  Calories
0      60.0  110.0     130.0     409.1
1      60.0  117.0     145.0     479.0
2      60.0  103.0     135.0     340.0
3      45.0  109.0     175.0     282.4
4      45.0   80.0     148.0     406.0

In [78]:
def strength(duration):
    mean_duration = df_training['Duration'].mean()
    if duration >= mean_duration:
        return 'Strong'
    else:
        return 'Weak'

In [85]:
mean_duration = df_training['Duration'].mean()
st = lambda duration: 'Strong' if duration >= mean_duration else 'Weak'

In [79]:
print(strength(45))

Weak

In [80]:
print(strength(80))

Strong

In [81]:
strengths = df_training['Duration'].apply(strength)
print(strengths)

0        Weak
1        Weak
2        Weak
3        Weak
4        Weak
        ...
167      Weak
168      Weak
169    Strong
170    Strong
171    Strong
Name: Duration, Length: 172, dtype: object

In [82]:
df_training['Strength'] = strengths
df_training.head()

   Duration  Pulse  Maxpulse  Calories Strength
0      60.0  110.0     130.0     409.1     Weak
1      60.0  117.0     145.0     479.0     Weak
2      60.0  103.0     135.0     340.0     Weak
3      45.0  109.0     175.0     282.4     Weak
4      45.0   80.0     148.0     406.0     Weak

In [83]:
# Viết tắt lại
df_training['Strength'] = df_training['Duration'].apply(strength)
df_training.head()

   Duration  Pulse  Maxpulse  Calories Strength
0      60.0  110.0     130.0     409.1     Weak
1      60.0  117.0     145.0     479.0     Weak
2      60.0  103.0     135.0     340.0     Weak
3      45.0  109.0     175.0     282.4     Weak
4      45.0   80.0     148.0     406.0     Weak

In [86]:
mean_duration = df_training['Duration'].mean()

df_training['Strength'] = df_training['Duration'].apply(lambda duration: 'Strong' if duration >= mean_duration else 'Weak')
df_training.head()

   Duration  Pulse  Maxpulse  Calories Strength
0      60.0  110.0     130.0     409.1     Weak
1      60.0  117.0     145.0     479.0     Weak
2      60.0  103.0     135.0     340.0     Weak
3      45.0  109.0     175.0     282.4     Weak
4      45.0   80.0     148.0     406.0     Weak