In [1]:
import pandas as pd
import numpy as np

In [2]:
df_diemthi = pd.DataFrame({
    'Grade': np.random.randint(50, 100, size=500)
})

In [3]:
df_diemthi.head()

   Grade
0     83
1     60
2     90
3     53
4     78

In [ ]:
# Lấy mâu ngẫu nhiên 50 dòng từ DataFrame, random_state để đảm bảo tính tái lập
df_sample = df_diemthi.sample(n=50, random_state=42)
df_sample.head()

     Grade
361     66
73      73
374     69
155     69
104     83

In [ ]:
# Thêm cột giới tính với giá trị ngẫu nhiên
df_diemthi['Gender'] = np.random.choice(['Male', 'Female'], size=len(df_diemthi))
df_diemthi.head()

   Grade  Gender
0     83    Male
1     60  Female
2     90  Female
3     53  Female
4     78    Male

In [38]:
n_males = len(df_diemthi[df_diemthi['Gender'] == 'Male'])
n_females = len(df_diemthi[df_diemthi['Gender'] == 'Female'])
print(f"Số lượng nam trong mẫu: {n_males}")
print(f"Số lượng nữ trong mẫu: {n_females}")

Số lượng nam trong mẫu: 248
Số lượng nữ trong mẫu: 252

In [44]:
# Lấy mẫu ngẫu nhiên 50 dòng từ Data
df_sample = df_diemthi.sample(n=50)
n_males = len(df_sample[df_sample['Gender'] == 'Male'])
n_females = len(df_sample[df_sample['Gender'] == 'Female'])
print(f"Số lượng nam trong mẫu: {n_males}")
print(f"Số lượng nữ trong mẫu: {n_females}")

Số lượng nam trong mẫu: 23
Số lượng nữ trong mẫu: 27

In [45]:
def random_sample(df, n_samples):
    return df.sample(n=n_samples)

df_groups = df_diemthi.groupby('Gender').apply(random_sample, n_samples=25)
# df_groups = df_diemthi.groupby('Gender').apply(lambda x: x.sample(n=25))
n_males = len(df_groups[df_groups['Gender'] == 'Male'])
n_females = len(df_groups[df_groups['Gender'] == 'Female'])
print(f"Số lượng nam trong mẫu nhóm: {n_males}")
print(f"Số lượng nữ trong mẫu nhóm: {n_females}")

Số lượng nam trong mẫu nhóm: 25
Số lượng nữ trong mẫu nhóm: 25

/var/folders/10/3dssf0p51vzgb7zfm9xl0vrm0000gn/T/ipykernel_99812/2134491227.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_groups = df_diemthi.groupby('Gender').apply(random_sample, n_samples=25)

In [46]:
start = np.random.choice(range(50), size=1)[0]
print(f"Chỉ số bắt đầu ngẫu nhiên: {start}")

Chỉ số bắt đầu ngẫu nhiên: 34

In [47]:
step = len(df_diemthi) // 50
print(f"Bước nhảy: {step}")

Bước nhảy: 10

In [48]:
df_steps = df_diemthi[start::step]
df_steps.head()

    Grade  Gender
34     64    Male
44     70    Male
54     86  Female
64     90    Male
74     82    Male

In [49]:
df_diemthi['School'] = np.random.choice(
    ['ĐH Bách Khoa', 
    'ĐH Kinh Tế', 
    'ĐH Ngoại Thương',
    'ĐH Xây Dựng',
    'ĐH Giao Thông',
    'ĐH Thủy Lợi',
    'ĐH FPT',
    'ĐH Công Nghệ',
    'ĐH Sư Phạm',
    'ĐH Ngoại Giao'], size=len(df_diemthi))

In [50]:
all_schools = df_diemthi['School'].unique()
print("Danh sách các trường học:", all_schools)

Danh sách các trường học: ['ĐH Ngoại Giao' 'ĐH Kinh Tế' 'ĐH Bách Khoa' 'ĐH Công Nghệ' 'ĐH Xây Dựng'
 'ĐH Ngoại Thương' 'ĐH Giao Thông' 'ĐH Sư Phạm' 'ĐH FPT' 'ĐH Thủy Lợi']

In [51]:
schools = np.random.choice(all_schools, size=3, replace=False)
print("Các trường học được chọn:", schools)

Các trường học được chọn: ['ĐH Ngoại Thương' 'ĐH Công Nghệ' 'ĐH FPT']

In [53]:
df_cluster = df_diemthi[df_diemthi['School'].isin(schools)]
df_cluster.head(10)

    Grade  Gender           School
3      53  Female     ĐH Công Nghệ
6      80    Male  ĐH Ngoại Thương
7      80    Male     ĐH Công Nghệ
10     63  Female  ĐH Ngoại Thương
11     66    Male     ĐH Công Nghệ
16     54    Male     ĐH Công Nghệ
17     57  Female  ĐH Ngoại Thương
19     59    Male     ĐH Công Nghệ
21     67    Male           ĐH FPT
23     55  Female           ĐH FPT