In [66]:
import pandas as pd

In [67]:
movies_df = pd.read_csv("movies.csv")
ratings_df = pd.read_csv("ratings.csv")

In [68]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [69]:
movies_df.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [70]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [71]:
ratings_df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [72]:
ratings_df.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [73]:
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [74]:
genres_example = 'Adventure|Animation|Children|Comedy|Fantasy'
genres_list = genres_example.split('|')
print(genres_list)

['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy']

In [75]:
movies_df['genres'] = movies_df['genres'].str.split('|')
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]"
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]"
4,5,Father of the Bride Part II (1995),[Comedy]

In [76]:
movies_df_encoded = movies_df.copy()
genres_cols = []

for index, row in movies_df_encoded.iterrows():
    genres_cols.append(index)
    for genre in row['genres']:
        movies_df_encoded.at[index, genre] = 1

movies_df_encoded.head()

,movieId,title,genres,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,...,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]",1.0,1.0,1.0,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]",1.0,NaN,1.0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Grumpier Old Men (1995),"[Comedy, Romance]",NaN,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]",NaN,NaN,NaN,1.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Father of the Bride Part II (1995),[Comedy],NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
movies_df_encoded.fillna(0, inplace=True)
movies_df_encoded.drop(columns=['genres'], inplace=True)
movies_df_encoded = movies_df_encoded.set_index('movieId')
movies_df_encoded.head()

,title,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,...,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
movieId,,,,,,,,,,,,,,,,,,,,,
1,Toy Story (1995),1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Jumanji (1995),1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Grumpier Old Men (1995),0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Waiting to Exhale (1995),0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Father of the Bride Part II (1995),0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
ratings_df.drop(columns=['timestamp'], inplace=True)
ratings_df.head()

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [79]:
tungdt_ratings = [
    {'movieId': 165, 'title': 'Die Hard: With a Vengeance (1995)', 'rating': 4},
    {'movieId': 208, 'title': 'Waterworld (1995)', 'rating': 4},
    {'movieId': 260, 'title': 'Star Wars: Episode IV - A New Hope (1977)', 'rating': 5},
    {'movieId': 5816, 'title': 'Harry Potter and the Chamber of Secrets (2002)', 'rating': 3},
    {'movieId': 8368, 'title': 'Harry Potter and the Prisoner of Azkaban (2004)', 'rating': 3},
    {'movieId': 25959, 'title': 'Annie Get Your Gun (1950)', 'rating': 2},
    {'movieId': 26590, 'title': 'G.I. Joe: The Movie (1987)', 'rating': 6},
    {'movieId': 27434, 'title': 'Darkness (2002)', 'rating': 2},
    {'movieId': 114335, 'title': 'La cravate (1957)', 'rating': 4},
    {'movieId': 130482, 'title': 'Too Late for Tears (1949)', 'rating': 3}
]
tungdt_ratings_df = pd.DataFrame(tungdt_ratings)
tungdt_ratings_df.head()

   movieId                                            title  rating
0      165                Die Hard: With a Vengeance (1995)       4
1      208                                Waterworld (1995)       4
2      260        Star Wars: Episode IV - A New Hope (1977)       5
3     5816   Harry Potter and the Chamber of Secrets (2002)       3
4     8368  Harry Potter and the Prisoner of Azkaban (2004)       3

In [80]:
tungdt_ids = movies_df[movies_df['movieId'].isin(tungdt_ratings_df['movieId'])]
tungdt_ids.head()

,movieId,title,genres
138,165,Die Hard: With a Vengeance (1995),"[Action, Crime, Thriller]"
176,208,Waterworld (1995),"[Action, Adventure, Sci-Fi]"
224,260,Star Wars: Episode IV - A New Hope (1977),"[Action, Adventure, Sci-Fi]"
4076,5816,Harry Potter and the Chamber of Secrets (2002),"[Adventure, Fantasy]"
5166,8368,Harry Potter and the Prisoner of Azkaban (2004),"[Adventure, Fantasy, IMAX]"

In [81]:
tungdt_ratings_df = pd.merge(tungdt_ratings_df, tungdt_ids, on='movieId')
tungdt_ratings_df.head()

,movieId,title_x,rating,title_y,genres
0,165,Die Hard: With a Vengeance (1995),4,Die Hard: With a Vengeance (1995),"[Action, Crime, Thriller]"
1,208,Waterworld (1995),4,Waterworld (1995),"[Action, Adventure, Sci-Fi]"
2,260,Star Wars: Episode IV - A New Hope (1977),5,Star Wars: Episode IV - A New Hope (1977),"[Action, Adventure, Sci-Fi]"
3,5816,Harry Potter and the Chamber of Secrets (2002),3,Harry Potter and the Chamber of Secrets (2002),"[Adventure, Fantasy]"
4,8368,Harry Potter and the Prisoner of Azkaban (2004),3,Harry Potter and the Prisoner of Azkaban (2004),"[Adventure, Fantasy, IMAX]"

In [82]:
tungdt_ratings_df['title'] = tungdt_ratings_df['title_x']
tungdt_ratings_df.drop(columns=['title_x', 'title_y'], inplace=True)
tungdt_ratings_df.head()

,movieId,rating,genres,title
0,165,4,"[Action, Crime, Thriller]",Die Hard: With a Vengeance (1995)
1,208,4,"[Action, Adventure, Sci-Fi]",Waterworld (1995)
2,260,5,"[Action, Adventure, Sci-Fi]",Star Wars: Episode IV - A New Hope (1977)
3,5816,3,"[Adventure, Fantasy]",Harry Potter and the Chamber of Secrets (2002)
4,8368,3,"[Adventure, Fantasy, IMAX]",Harry Potter and the Prisoner of Azkaban (2004)

In [83]:
print(movies_df_encoded.columns.tolist())

['title', 'Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy', 'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Mystery', 'Sci-Fi', 'War', 'Musical', 'Documentary', 'IMAX', 'Western', 'Film-Noir', '(no genres listed)']

In [84]:
tungdt_ratings_genres = movies_df_encoded[movies_df_encoded.title.isin(tungdt_ratings_df['title'])]

In [85]:
tungdt_ratings_genres.shape

(10, 21)

In [86]:
tungdt_ratings_genres.head()

,title,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,...,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
movieId,,,,,,,,,,,,,,,,,,,,,
165,Die Hard: With a Vengeance (1995),0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
208,Waterworld (1995),1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
260,Star Wars: Episode IV - A New Hope (1977),1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5816,Harry Potter and the Chamber of Secrets (2002),1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8368,Harry Potter and the Prisoner of Azkaban (2004),1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [87]:
# tungdt_ratings_df = tungdt_ratings_df.set_index('movieId')
# tungdt_ratings_genres = tungdt_ratings_df.drop(columns=['title'])
# tungdt_ratings_genres.head()

In [88]:
tungdt_ratings_genres = tungdt_ratings_genres.drop(columns=['title'])
tungdt_ratings_genres.reset_index(drop=True, inplace=True)
tungdt_ratings_genres.head()

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [89]:
print(tungdt_ratings_genres.shape)

(10, 20)

In [90]:
print(tungdt_ratings_df.shape)

(10, 4)

In [91]:
print(tungdt_ratings_df['rating'])

0    4
1    4
2    5
3    3
4    3
5    2
6    6
7    2
8    4
9    3
Name: rating, dtype: int64

In [92]:
tungdt_profile = tungdt_ratings_genres.T.dot(tungdt_ratings_df['rating'])
print(tungdt_profile)

Adventure             21.0
Animation              6.0
Children               6.0
Comedy                 2.0
Fantasy               12.0
Romance                2.0
Drama                  3.0
Action                19.0
Crime                  7.0
Thriller               7.0
Horror                 2.0
Mystery                5.0
Sci-Fi                15.0
War                    0.0
Musical                2.0
Documentary            0.0
IMAX                   3.0
Western                2.0
Film-Noir              3.0
(no genres listed)     4.0
dtype: float64

In [93]:
movies_df_encoded = movies_df_encoded.drop(columns=['title'])
movies_df_encoded.head()

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
movieId,,,,,,,,,,,,,,,,,,,,
1,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [94]:
print(movies_df_encoded.shape)

(9742, 20)

In [95]:
tungdt_recommendation = movies_df_encoded.dot(tungdt_profile)
tungdt_recommendation.head()

movieId
1    47.0
2    39.0
3     4.0
4     7.0
5     2.0
dtype: float64

In [96]:
tungdt_recommendation.sort_values(ascending=False).head(10)

movieId
52462     80.0
27155     79.0
71999     79.0
6350      79.0
26590     79.0
164226    76.0
161594    76.0
62956     75.0
546       75.0
177285    73.0
dtype: float64

In [99]:
top_recommendations = tungdt_recommendation.sort_values(ascending=False).head(10)
print(top_recommendations)

movieId
52462     80.0
27155     79.0
71999     79.0
6350      79.0
26590     79.0
164226    76.0
161594    76.0
62956     75.0
546       75.0
177285    73.0
dtype: float64

In [100]:
# get movie titles for the top recommendations
top_movie_ids = top_recommendations.index
top_movie_titles = movies_df[movies_df['movieId'].isin(top_movie_ids)]['title']
print(top_movie_titles)

478                              Super Mario Bros. (1993)
4348    Laputa: Castle in the Sky (Tenkû no shiro Rapy...
5533                           G.I. Joe: The Movie (1987)
5620                    Batman/Superman Movie, The (1998)
6462    Aqua Teen Hunger Force Colon Movie Film for Th...
6879                       Futurama: Bender's Game (2008)
7170            Aelita: The Queen of Mars (Aelita) (1924)
9358                 Kingsglaive: Final Fantasy XV (2016)
9394                                  Maximum Ride (2016)
9617     Sword Art Online The Movie: Ordinal Scale (2017)
Name: title, dtype: object